### ISSUE TITLE
When the nodes are too small it doesn't pick up the draw

### ISSUE THREAD

**Issue by akbarsha03** [TakWolf/Android-Lock9View#6]
I've a very small nodes like following 

![device-2015-10-05-201114](https://cloud.githubusercontent.com/assets/4894571/10283490/6bf01e86-6b9d-11e5-8f0e-9062696c7fc7.png)

Nodes are drawn only If the finger touches the node. Doesn't draw even if the finger is too close to the node. The default android lock pattern of the **in built android security** will draw the line even if the finger is 10dp *(not sure how much dp it is actually)* away from the node.

Can you please add feature where I can set the touch area to be bigger but the drawable of the node is smaller.

**Comment by TakWolf** [comment]
The problem is that you want to draw a small node but want the touch area is bigger ? Now there is no feature to set the touch area special yet, but you can try this way temporarily: make your drawable size bigger with alpha blank, like this:

![saf1](https://cloud.githubusercontent.com/assets/6064962/10285125/fb6c5aea-6bb9-11e5-860a-48dd60a0037f.png)
![-1](https://cloud.githubusercontent.com/assets/6064962/10285126/fb6db17e-6bb9-11e5-84c8-3c6f032c0dd2.png)

**Comment by akbarsha03** [comment]
@TakWolf This will solve my issue as you said. But Each time I've to modify thePNG file when I need to adjust the drawable size. Hence I'm requesting the feature to be added.

**Comment by TakWolf** [comment]
OK, gave me a little time to do this work.

**Comment by akbarsha03** [comment]
@TakWolf thank you so much. Waiting for your implementation :smiley:

**Comment by TakWolf** [comment]
compile 'com.takwolf.android:lock9view:0.0.8'

I have add this feature and some other things, please see readme.

I guess you will glad to see this example :
https://github.com/TakWolf/Android-Lock9View/blob/master/app/src/main/res/layout/activity_l_style.xml

**Comment by akbarsha03** [comment]
@TakWolf Thank you so much. Coding the changes now :+1:

**Comment by akbarsha03** [comment]
@TakWolf Thank you so much again. Implemented :100:
